image: lroc/fortify-tools

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script: echo "Running tests"

build:
  stage: build
  script:
    - echo "Building the app"

deploy_staging:
  stage: deploy
  script:
    - echo "Deploy to staging server" > helloworld.log
  only:
    - master