image: lroc/fortify-tools:latest

stages:
  - test
  - build
  - deploy

test:
  stage: test
  script: echo "Running tests"

build:
  stage: build
  script:
    - mvn clean package -DskipTests
    - echo "Building the app"

deploy_staging:
  stage: deploy
  script:
    - echo "Deploy to staging server" > helloworld.log
    - wget http://192.168.3.25:8888/index
  only:
    - master